#!/usr/bin/env bash
# script that installs Nginx server and redirects /redirect_me to
# another page
# The redirection must be a “301 Moved Permanently”
sudo apt-get -y update
sudo apt-get -y upgread
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen \[::\]:80 default_server;/a rewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
